const obj = {};
let route = [
    { "index": "1-1", "open": "1", "path": "/home/order/manage", "name": '订单管理' },
    { "index": "1-2", "open": "1", "path": "/home/order/clientInfo", "name": '客户信息' },
    // {"index":"1-3","open":"1","path":"/home/index","name":'系统对照'},
    // {"index":"1-4","open":"1","path":"/home/index","name":'发票管理'},
    // {"index":"1-5","open":"1","path":"/home/index","name":'快递公司'},
    // {"index":"1-6","open":"1","path":"/home/index","name":'其他订单'},
    // {"index":"1-7","open":"1","path":"/home/index","name":'店铺查询'},
    // {"index":"1-8","open":"1","path":"/home/index","name":'运费管理'},
    { "index": "2-1", "open": "2", "path": "/home/record/craft", "name": '工艺' },
    { "index": "2-2", "open": "2", "path": "/home/record/embroid", "name": '刺绣' },
    { "index": "2-3", "open": "2", "path": "/home/record/bodyPart", "name": '量体部位' },
    { "index": "2-4", "open": "2", "path": "/home/record/special", "name": '特体' },
    { "index": "2-5", "open": "2", "path": "/home/record/attireStyle", "name": '着装风格' },
    { "index": "2-6", "open": "2", "path": "/home/record/accidentStyle", "name": '长短款' },
    { "index": "2-7", "open": "2", "path": "/home/record/designStyle", "name": '款式风格' },
    { "index": "2-8", "open": "2", "path": "/home/record/system", "name": '系统档案' },
    { "index": "2-9", "open": "2", "path": "/home/record/size", "name": "尺寸管理" },
    { "index": "3-1", "open": "3", "path": "/home/fabric/info", "name": '面料信息' },
    { "index": "3-2", "open": "3", "path": "/home/fabric/price", "name": '面料价格' },
    { "index": "4-1", "open": "4", "path": "/home/design/manage", "name": '款式管理' },
    { "index": "5-1", "open": "5", "path": "/home/personModel/info", "name": '人体模式信息' },
    { "index": "6-1", "open": "6", "path": "/home/problem/manage", "name": '问题管理' },
    { "index": "7-1", "open": "7", "path": "/home/modelManage/infoManage", "name": '人体模型信息' },
    { "index": "7-2", "open": "7", "path": "/home/modelManage/anchor", "name": '锚点管理' },
    { "index": "8-1", "open": "8", "path": "/home/system/user", "name": '用户管理' },
    { "index": "8-2", "open": "8", "path": "/home/system/menu", "name": '菜单管理' },
    { "index": "8-3", "open": "8", "path": "/home/system/part", "name": '角色管理' },
    { "index": "12", "open": "12", "path": "/home/index", "name": '图片' },
    { "index": "9-1", "open": "9", "path": "/home/cashier/cashier-form", "name": 'cashier-form' },
    { "index": "9-3", "open": "9", "path": "/home/cashier/cashier-staff", "name": 'cashier-staff' },
    { "index": "9-4", "open": "9", "path": "/home/cashier/cashier-store", "name": 'cashier-store' },
    { "index": "9-5", "open": "9", "path": "/home/cashier/coupon", "name": 'coupon' },
    { "index": "9-6", "open": "9", "path": "/home/cashier/activity", "name": 'activity' },
    { "index": "9-2", "open": "9", "path": "/home/cashier/cotal-list", "name": 'cotal-list' },
    { "index": "10-1", "open": "10", "path": "/home/fabric/goods", "name": '物料管理' },
    { "index": "10-2", "open": "10", "path": "/home/fabric/allot", "name": '调拨管理' },
    { "index": "11-1", "open": "11", "path": "/home/supplier/supplier-manage", "name": '供应商管理' },
    { "index": "13-1", "open": "13", "path": "/home/warehouse/warehouse-into", "name": '入库管理' },
    { "index": "13-2", "open": "13", "path": "/home/warehouse/warehouse-out", "name": '出库管理' },
    { "index": "13-3", "open": "13", "path": "/home/warehouse/case-tend", "name": '仓库维护' },
];
export default route